name: Test
on:
  pull_request:
    branches:
    - master
jobs:
    test:
        name: Test
        if: github.actor != 'github-actions[bot]'
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                ref: ${{ github.event.pull_request.head.sha }}
            - name: Commit
              run: |
                date > date.txt
                git config set user.name "github-actions[bot]"
                git config set user.email actions@github.invalid
                git add date.txt
                git commit -m "Test"
                git push