name: Test
on: push
jobs:
    test:
        name: Test
        runs-on: ubuntu-24.04
        steps:
            - name: Commit
              run: |
                date > date.txt
                git config set user.name Github
                git config set user.email github@github.invalid
                git add date.txt
                git commit -m "Test"
                git push